import { Transaction, KpiData, ChartDataPoint, SpendingCategory } from './types';

export const mockTransactions: Transaction[] = [
  {
    id: 'TXN-001',
    date: '2024-03-28',
    description: 'Monthly Salary Deposit',
    category: 'Employment',
    amount: 4200.00,
    type: 'income',
    status: 'completed',
    account: 'Primary Checking',
  },
  {
    id: 'TXN-002',
    date: '2024-03-27',
    description: 'Apartment Rent Payment',
    category: 'Housing',
    amount: -1850.00,
    type: 'expense',
    status: 'completed',
    account: 'Primary Checking',
  },
  {
    id: 'TXN-003',
    date: '2024-03-26',
    description: 'Whole Foods Market',
    category: 'Groceries',
    amount: -124.50,
    type: 'expense',
    status: 'completed',
    account: 'Credit Card',
  },
  {
    id: 'TXN-004',
    date: '2024-03-25',
    description: 'Tesla, Inc. Stock Dividend',
    category: 'Investments',
    amount: 340.00,
    type: 'income',
    status: 'completed',
    account: 'Investment Portfolio',
  },
  {
    id: 'TXN-005',
    date: '2024-03-24',
    description: 'Netflix Premium',
    category: 'Entertainment',
    amount: -22.99,
    type: 'expense',
    status: 'completed',
    account: 'Credit Card',
  },
  {
    id: 'TXN-006',
    date: '2024-03-23',
    description: 'Freelance Design Contract',
    category: 'Freelance',
    amount: 950.00,
    type: 'income',
    status: 'completed',
    account: 'Business Account',
  },
  {
    id: 'TXN-007',
    date: '2024-03-22',
    description: 'Uber Eats Delivery',
    category: 'Dining',
    amount: -38.75,
    type: 'expense',
    status: 'completed',
    account: 'Credit Card',
  },
  {
    id: 'TXN-008',
    date: '2024-03-21',
    description: 'Transfer to Savings',
    category: 'Transfer',
    amount: -500.00,
    type: 'transfer',
    status: 'completed',
    account: 'Primary Checking',
  },
  {
    id: 'TXN-009',
    date: '2024-03-20',
    description: 'AWS Cloud Services',
    category: 'Technology',
    amount: -89.00,
    type: 'expense',
    status: 'pending',
    account: 'Business Account',
  },
  {
    id: 'TXN-010',
    date: '2024-03-19',
    description: 'Consulting Invoice #142',
    category: 'Consulting',
    amount: 1800.00,
    type: 'income',
    status: 'pending',
    account: 'Business Account',
  },
  {
    id: 'TXN-011',
    date: '2024-03-18',
    description: 'Delta Airlines Flight',
    category: 'Travel',
    amount: -342.00,
    type: 'expense',
    status: 'completed',
    account: 'Credit Card',
  },
  {
    id: 'TXN-012',
    date: '2024-03-17',
    description: 'Spotify Family Plan',
    category: 'Entertainment',
    amount: -16.99,
    type: 'expense',
    status: 'completed',
    account: 'Credit Card',
  },
  {
    id: 'TXN-013',
    date: '2024-03-15',
    description: 'Electric & Gas Utilities',
    category: 'Utilities',
    amount: -145.20,
    type: 'expense',
    status: 'completed',
    account: 'Primary Checking',
  },
  {
    id: 'TXN-014',
    date: '2024-03-14',
    description: 'Gym Membership',
    category: 'Health',
    amount: -55.00,
    type: 'expense',
    status: 'failed',
    account: 'Credit Card',
  },
  {
    id: 'TXN-015',
    date: '2024-03-12',
    description: 'Apple App Store Revenue',
    category: 'Investments',
    amount: 218.45,
    type: 'income',
    status: 'completed',
    account: 'Business Account',
  },
];

export const kpiData: KpiData = {
  totalBalance: 24560.00,
  totalIncome: 4200.00,
  totalExpenses: 2100.00,
  netSavings: 2100.00,
  balanceChange: 8.4,
  incomeChange: 15.2,
  expensesChange: -8.0,
  savingsChange: 12.3,
};

export const chartData: ChartDataPoint[] = [
  { month: 'Oct', income: 3800, expenses: 2400, balance: 19200 },
  { month: 'Nov', income: 4100, expenses: 2200, balance: 21100 },
  { month: 'Dec', income: 5200, expenses: 3100, balance: 23200 },
  { month: 'Jan', income: 3900, expenses: 2500, balance: 24600 },
  { month: 'Feb', income: 4400, expenses: 2300, balance: 26700 },
  { month: 'Mar', income: 4200, expenses: 2100, balance: 24560 },
];

export const spendingCategories: SpendingCategory[] = [
  { name: 'Housing', amount: 1850, percentage: 36, color: '#1e293b' },
  { name: 'Travel', amount: 342, percentage: 16, color: '#006c49' },
  { name: 'Groceries', amount: 245, percentage: 12, color: '#4edea3' },
  { name: 'Dining', amount: 186, percentage: 9, color: '#bcc7de' },
  { name: 'Utilities', amount: 145, percentage: 7, color: '#45474c' },
  { name: 'Entertainment', amount: 124, percentage: 6, color: '#5a0008' },
  { name: 'Technology', amount: 89, percentage: 4, color: '#930013' },
  { name: 'Health', amount: 115, percentage: 6, color: '#75777d' },
  { name: 'Other', amount: 82, percentage: 4, color: '#c5c6cd' },
];

export const categoryIcons: Record<string, string> = {
  Employment: '💼',
  Housing: '🏠',
  Groceries: '🛒',
  Investments: '📈',
  Entertainment: '🎬',
  Freelance: '💻',
  Dining: '🍔',
  Transfer: '↔️',
  Technology: '⚙️',
  Consulting: '🏛️',
  Travel: '✈️',
  Utilities: '⚡',
  Health: '💊',
};
